const a0Vocabulary = [
  { english: "Hello", spanish: "Hola", category: "Greetings" },
  { english: "Hi", spanish: "Hola", category: "Greetings" },
  { english: "Good morning", spanish: "Buenos días", category: "Greetings" },
  { english: "Good afternoon", spanish: "Buenas tardes", category: "Greetings" },
  { english: "Good evening", spanish: "Buenas noches", category: "Greetings" },
  { english: "Goodbye", spanish: "Adiós", category: "Greetings" },
  { english: "See you later", spanish: "Hasta luego", category: "Greetings" },
  { english: "Nice to meet you", spanish: "Mucho gusto", category: "Greetings" },

  { english: "Mother", spanish: "Madre", category: "Family" },
  { english: "Father", spanish: "Padre", category: "Family" },
  { english: "Brother", spanish: "Hermano", category: "Family" },
  { english: "Sister", spanish: "Hermana", category: "Family" },
  { english: "Grandmother", spanish: "Abuela", category: "Family" },
  { english: "Grandfather", spanish: "Abuelo", category: "Family" },
  { english: "Aunt", spanish: "Tía", category: "Family" },
  { english: "Uncle", spanish: "Tío", category: "Family" },
  { english: "Cousin", spanish: "Primo / prima", category: "Family" },
  { english: "Family", spanish: "Familia", category: "Family" },

  { english: "Peru", spanish: "Perú", category: "Countries" },
  { english: "Peruvian", spanish: "Peruano / peruana", category: "Countries" },
  { english: "France", spanish: "Francia", category: "Countries" },
  { english: "French", spanish: "Francés / francesa", category: "Countries" },
  { english: "Canada", spanish: "Canadá", category: "Countries" },
  { english: "Canadian", spanish: "Canadiense", category: "Countries" },
  { english: "United States", spanish: "Estados Unidos", category: "Countries" },
  { english: "American", spanish: "Estadounidense", category: "Countries" },

  { english: "Red", spanish: "Rojo", category: "Colors" },
  { english: "Blue", spanish: "Azul", category: "Colors" },
  { english: "Green", spanish: "Verde", category: "Colors" },
  { english: "Yellow", spanish: "Amarillo", category: "Colors" },
  { english: "Black", spanish: "Negro", category: "Colors" },
  { english: "White", spanish: "Blanco", category: "Colors" },
  { english: "Orange", spanish: "Naranja", category: "Colors" },
  { english: "Purple", spanish: "Morado", category: "Colors" },
  { english: "Pink", spanish: "Rosado", category: "Colors" },
  { english: "Brown", spanish: "Marrón", category: "Colors" },

  { english: "Book", spanish: "Libro", category: "Objects" },
  { english: "Pen", spanish: "Lapicero", category: "Objects" },
  { english: "Pencil", spanish: "Lápiz", category: "Objects" },
  { english: "Notebook", spanish: "Cuaderno", category: "Objects" },
  { english: "Phone", spanish: "Teléfono", category: "Objects" },
  { english: "Computer", spanish: "Computadora", category: "Objects" },
  { english: "Table", spanish: "Mesa", category: "Objects" },
  { english: "Chair", spanish: "Silla", category: "Objects" },
  { english: "Bag", spanish: "Bolso / mochila", category: "Objects" },
  { english: "Bottle", spanish: "Botella", category: "Objects" },

  { english: "Water", spanish: "Agua", category: "Food" },
{ english: "Bread", spanish: "Pan", category: "Food" },
{ english: "Rice", spanish: "Arroz", category: "Food" },
{ english: "Chicken", spanish: "Pollo", category: "Food" },
{ english: "Fish", spanish: "Pescado", category: "Food" },
{ english: "Apple", spanish: "Manzana", category: "Food" },
{ english: "Banana", spanish: "Plátano", category: "Food" },
{ english: "Coffee", spanish: "Café", category: "Food" },
{ english: "Milk", spanish: "Leche", category: "Food" },
{ english: "Juice", spanish: "Jugo", category: "Food" },

{ english: "Teacher", spanish: "Profesor", category: "School" },
{ english: "Student", spanish: "Estudiante", category: "School" },
{ english: "Classroom", spanish: "Salón", category: "School" },
{ english: "Homework", spanish: "Tarea", category: "School" },
{ english: "Exam", spanish: "Examen", category: "School" },
{ english: "Lesson", spanish: "Lección", category: "School" },
{ english: "Question", spanish: "Pregunta", category: "School" },
{ english: "Answer", spanish: "Respuesta", category: "School" },

{ english: "Doctor", spanish: "Doctor", category: "Jobs" },
{ english: "Engineer", spanish: "Ingeniero", category: "Jobs" },
{ english: "Teacher", spanish: "Profesor", category: "Jobs" },
{ english: "Programmer", spanish: "Programador", category: "Jobs" },
{ english: "Actor", spanish: "Actor", category: "Jobs" },
{ english: "Nurse", spanish: "Enfermero", category: "Jobs" },
{ english: "Chef", spanish: "Chef", category: "Jobs" },
{ english: "Police Officer", spanish: "Policía", category: "Jobs" },

{ english: "Wake up", spanish: "Despertarse", category: "Daily Life" },
{ english: "Sleep", spanish: "Dormir", category: "Daily Life" },
{ english: "Eat", spanish: "Comer", category: "Daily Life" },
{ english: "Drink", spanish: "Beber", category: "Daily Life" },
{ english: "Study", spanish: "Estudiar", category: "Daily Life" },
{ english: "Work", spanish: "Trabajar", category: "Daily Life" },
{ english: "Read", spanish: "Leer", category: "Daily Life" },
{ english: "Write", spanish: "Escribir", category: "Daily Life" },
{ english: "Go", spanish: "Ir", category: "Daily Life" },
{ english: "Come", spanish: "Venir", category: "Daily Life" },

{ english: "House", spanish: "Casa", category: "Places" },
{ english: "School", spanish: "Escuela", category: "Places" },
{ english: "University", spanish: "Universidad", category: "Places" },
{ english: "Restaurant", spanish: "Restaurante", category: "Places" },
{ english: "Hospital", spanish: "Hospital", category: "Places" },
{ english: "Bank", spanish: "Banco", category: "Places" },
{ english: "Park", spanish: "Parque", category: "Places" },
{ english: "Store", spanish: "Tienda", category: "Places" },
{ english: "Street", spanish: "Calle", category: "Places" },
{ english: "City", spanish: "Ciudad", category: "Places" },

{ english: "Zero", spanish: "Cero", category: "Numbers" },
{ english: "One", spanish: "Uno", category: "Numbers" },
{ english: "Two", spanish: "Dos", category: "Numbers" },
{ english: "Three", spanish: "Tres", category: "Numbers" },
{ english: "Four", spanish: "Cuatro", category: "Numbers" },
{ english: "Five", spanish: "Cinco", category: "Numbers" },
{ english: "Six", spanish: "Seis", category: "Numbers" },
{ english: "Seven", spanish: "Siete", category: "Numbers" },
{ english: "Eight", spanish: "Ocho", category: "Numbers" },
{ english: "Nine", spanish: "Nueve", category: "Numbers" },
{ english: "Ten", spanish: "Diez", category: "Numbers" },

{ english: "Day", spanish: "Día", category: "Time" },
{ english: "Week", spanish: "Semana", category: "Time" },
{ english: "Month", spanish: "Mes", category: "Time" },
{ english: "Year", spanish: "Año", category: "Time" },
{ english: "Today", spanish: "Hoy", category: "Time" },
{ english: "Tomorrow", spanish: "Mañana", category: "Time" },
{ english: "Yesterday", spanish: "Ayer", category: "Time" },
{ english: "Morning", spanish: "Mañana", category: "Time" },
{ english: "Afternoon", spanish: "Tarde", category: "Time" },
{ english: "Night", spanish: "Noche", category: "Time" },

{ english: "Car", spanish: "Auto", category: "Transportation" },
{ english: "Bus", spanish: "Bus", category: "Transportation" },
{ english: "Train", spanish: "Tren", category: "Transportation" },
{ english: "Taxi", spanish: "Taxi", category: "Transportation" },
{ english: "Bicycle", spanish: "Bicicleta", category: "Transportation" },
{ english: "Motorcycle", spanish: "Motocicleta", category: "Transportation" },
{ english: "Airport", spanish: "Aeropuerto", category: "Transportation" },
{ english: "Station", spanish: "Estación", category: "Transportation" },

{ english: "Music", spanish: "Música", category: "Hobbies" },
{ english: "Guitar", spanish: "Guitarra", category: "Hobbies" },
{ english: "Piano", spanish: "Piano", category: "Hobbies" },
{ english: "Football", spanish: "Fútbol", category: "Hobbies" },
{ english: "Basketball", spanish: "Baloncesto", category: "Hobbies" },
{ english: "Reading", spanish: "Lectura", category: "Hobbies" },
{ english: "Writing", spanish: "Escritura", category: "Hobbies" },
{ english: "Traveling", spanish: "Viajar", category: "Hobbies" },
{ english: "Photography", spanish: "Fotografía", category: "Hobbies" },
{ english: "Movies", spanish: "Películas", category: "Hobbies" },

{ english: "Computer", spanish: "Computadora", category: "Technology" },
{ english: "Laptop", spanish: "Laptop", category: "Technology" },
{ english: "Phone", spanish: "Teléfono", category: "Technology" },
{ english: "Internet", spanish: "Internet", category: "Technology" },
{ english: "Robot", spanish: "Robot", category: "Technology" },
{ english: "Program", spanish: "Programa", category: "Technology" },
{ english: "Website", spanish: "Página web", category: "Technology" },
{ english: "Application", spanish: "Aplicación", category: "Technology" },
{ english: "Password", spanish: "Contraseña", category: "Technology" },
{ english: "Software", spanish: "Software", category: "Technology" },

{ english: "Sun", spanish: "Sol", category: "Weather" },
{ english: "Rain", spanish: "Lluvia", category: "Weather" },
{ english: "Cloud", spanish: "Nube", category: "Weather" },
{ english: "Wind", spanish: "Viento", category: "Weather" },
{ english: "Hot", spanish: "Caluroso", category: "Weather" },
{ english: "Cold", spanish: "Frío", category: "Weather" },
{ english: "Weather", spanish: "Clima", category: "Weather" },
{ english: "Summer", spanish: "Verano", category: "Weather" },
{ english: "Winter", spanish: "Invierno", category: "Weather" },
{ english: "Spring", spanish: "Primavera", category: "Weather" }
];

